apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jju0xav64-nodejs
  janus-idp.io/tekton: jju0xav64-nodejs
  backstage.io/kubernetes-id: jju0xav64-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jju0xav64-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
