apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jju0xav64-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jju0xav64-nodejs 
  name: jju0xav64-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jju0xav64-nodejs 
